
CREATE SCHEMA IF NOT EXISTS pweb;

USE pweb;

CREATE TABLE IF NOT EXISTS PRODUTO (

  ID INT /*! AUTO_INCREMENT */,
  NOME VARCHAR(100),
  PRECO DECIMAL(14,4),
  UNIDADE VARCHAR(100),
  QUANTIDADE INT,

  PRIMARY KEY (ID)

);

INSERT INTO PRODUTO (ID, NOME, PRECO, UNIDADE, QUANTIDADE)

VALUES
  (1, "Sabão em Pó", 2.25, "Kg", 100),
  (2, "Sabão em Pedra", 2.00, "g", 99),
  (3, "Boneca Barbie", 202.99, "Un", 99),
  (4, "Play Station II", 999.99, "Un", 99)

ON DUPLICATE KEY UPDATE
  NOME = VALUES(NOME),
  PRECO = VALUES(PRECO),
  UNIDADE = VALUES(UNIDADE),
  QUANTIDADE = VALUES(QUANTIDADE);
